[package]
name = "anthropical"
description = "A lightweight, pure-Rust crate for Claude'ing it up."
version = "0.0.1"
edition = "2024"
repository = "https://github.com/xandwr/anthropical"
rust-version = "1.96.0"
keywords = ["anthropic", "claude", "api", "llm"]
categories = ["api-bindings", "artificial-intelligence"]
publish = false # for now...

[dependencies]
ureq = { version = "3.3.0", default-features = false, features = ["rustls"] }
serde_json = "1"